[package]
name        = "tether-map"
version     = "0.1.0"
edition     = "2024"
license     = "MIT OR Apache-2.0"
description = "A no-std compatible linked hashmap implementation."

[lib]
path = "src/lib.rs"

[features]
default            = [ "std", "iter-mut" ]
std                = [  ]
internal-debugging = [  ]
iter-mut           = [  ]

[profile.release-with-debug]
inherits = "release"
debug    = "full"

[dependencies]
hashbrown = { version = "0.15.5", default-features = false, features = [ "inline-more", "default-hasher" ] }

[dev-dependencies]
criterion = "0.7.0"
hashlink  = "0.10.0"
indexmap  = "2.11.0"
ntest     = "0.9.3"
rand      = "0.9.2"

[[bench]]
name    = "common_benchmarks"
harness = false
